#### NumPy is a fundamental package for scientific computing in python. It is a Python Library that provides a multi Dimensional Array object and various derived objects like masked arrays or matrices and an assortment of routines for fast operations on Arrays including Mathematical, Logical, Shape Manipulation, Sorting, Selecting, I/O, Discrete Fourier Transform, Basic Linear Algebra, Statistical Operations, Random Simulation, etc.

#### At the core of NumPy package is the N-dimensional Array object

## why NumPy ?

#### 2008-2009, Data Science ---> Matlab, R language (for developing DS models)

#### at that time, python existed but not the library: NumPy
#### python had Data types: list, dict which are slow
Syntax ---> python ---> Easy
##  We needed Speed and less Memory to work with huge amounts of data

NumPy ---> was written in C language ---> Wrapped to form a library in Python : NumPy
## NumPy ---> syntax ---> Easy for begginers ---> performing Scientific Calculations ---> creating Multi Dimensional Arrays ---> speed is faster for applying operations ---> less memory  

## Libraries like Scikit Learn, Tensorflow, and Pytorch require input data in Numpy Arrays or tensors.


## NumPy Arrays vs Python Sequences

#### NumPy Arrays have a fixed size at creation, unlike Python lists which grow dynamically. Changing the size of an n-dimensional array will create a new array and delete the original

#### The elements in a numpy array are required to be of the same data type, and hence each element will occupy same size in memory

#### NumPy Arrays facilitate advanced Mathemetical and other types of operations on large number of data. Typically, such operations are executed more efficiently with less code than is possible using Python's built-in sequences

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
numpy_array = np.array([1,2,3,4,5])

In [5]:
numpy_array

array([1, 2, 3, 4, 5])

In [7]:
type(numpy_array)  # ndarray -> n dimensional array

numpy.ndarray

In [8]:
TwoDArray = np.array([[1,2,3],[4,5,6]])

In [9]:
print(TwoDArray)

[[1 2 3]
 [4 5 6]]


In [12]:
TwoDArray2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
print(TwoDArray2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
TwoDArray3 = np.array([[1,2,3,11,12],[4,5,6,13,14],[7,8,9]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [18]:
TwoDArray4 = np.array([[1,2,3,11,12],[4,5,6,13,14],[7,8,9,15,16]])

In [20]:
print(TwoDArray4) # can't have inhomogenious size. It has to be of m*n

[[ 1  2  3 11 12]
 [ 4  5  6 13 14]
 [ 7  8  9 15 16]]


In [23]:
ThreeDArray = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [24]:
print(ThreeDArray)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
ThreeDArray = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [27]:
print(ThreeDArray)  # x-2, y=2, z=3   
# necessity is : x=y

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


#### np.array()  ---> creating multi-dimensional arrays

#### dtype parameter : which can help us out with deciding about the size of the data we are going to store inside the array 

In [28]:
np.array([1,2,3,4,5], dtype = np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [29]:
np.array([7,8,9,10,11,12], dtype = np.int64)

array([ 7,  8,  9, 10, 11, 12])

In [30]:
## np.float32, np.float64

In [31]:
np.array([11,15,16,17], dtype=float) # dtype -> datatype, size alloting for each element in array

array([11., 15., 16., 17.])

In [32]:
np.array([11,15,16,17], dtype = int)

array([11, 15, 16, 17])

In [33]:
np.array([11,15,16,17], dtype = bool)

array([ True,  True,  True,  True])

In [34]:
empty_list = []
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [36]:
np.arange(16)  # unhi sb ka 0 se 15 tk ka array bana lo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### arange --> It helps us out with providing the values over a certain range

In [37]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [38]:
np.arange(5,21)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [41]:
arange_data = np.arange(1,17)

In [42]:
# arange_data -> numpy array of size 1*16
arange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
print(arange_data)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [45]:
arange_data.reshape(2,8)  #(rows,columns)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

### np.reshape() ---> It helps us out with changing the shape of the array as per our needs

In [47]:
arange_data.reshape(2,10) # error since rows*columns should be equal to size 

ValueError: cannot reshape array of size 16 into shape (2,10)

In [50]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [52]:
## ones() ---> builds a numpy array with all elements equal to 1

In [58]:
np.ones((4,4)) # has got tuple as parameter
# by default float

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
# np.zeros()

In [60]:
np.zeros((4,5))  #by default float

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### random() ---> helps us out with generating any random values from 0 to 1 inside our matrix 

In [62]:
np.random.random((4,5))

array([[0.57261935, 0.12561142, 0.9875085 , 0.03952027, 0.19471297],
       [0.99018906, 0.26731189, 0.42875553, 0.52511215, 0.20654884],
       [0.38798997, 0.71966611, 0.86846269, 0.781351  , 0.59718888],
       [0.05642454, 0.45355281, 0.20932321, 0.58430539, 0.80090317]])

In [63]:
## identity()  ---> It helps us out with creating the matrix as an identity maatrix

In [66]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
np.identity(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### linspace()----> it makes sure that every value with the given range is going to have similar distance from eachother

In [73]:
np.linspace(-10,10,10) # (start, end, how many)
# numpy array with 10 values including start and end

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

# Attributes

In [74]:
# ndim -> stands for n dimension

In [75]:
arr = np.array([1,2,3])

In [76]:
arr

array([1, 2, 3])

In [77]:
arr.ndim

1

In [78]:
arrayy = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [79]:
arrayy

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [80]:
arrayy.ndim

3

In [81]:
np.array([[1,2],[3,4]]).ndim

2

In [82]:
## shape --> It provides us with the idea about the rows, columns in our dataset, or in array

In [83]:
ARray = np.array([[1,3,5],[4,5,6],[11,15,13]])

In [84]:
ARray

array([[ 1,  3,  5],
       [ 4,  5,  6],
       [11, 15, 13]])

In [85]:
ARray.shape

(3, 3)

In [86]:
ThreeDArray = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

In [87]:
ThreeDArray.shape

(2, 2, 2)

In [88]:
## size  --->  Total Number of Elements present inside our Dataset or Array

In [89]:
array_elements = np.arange(5,57)

In [92]:
array_elements.size

52

In [102]:
np.array([[1,2],[3,4],[5,8]]).itemsize  # telling in bytes # default is int64 if int

8

In [103]:
np.array([[1,2],[3,4],[5,6]], dtype = np.int32).itemsize

4

In [104]:
np.array([[1,2],[3,4],[5,6]], dtype = np.int64).itemsize

8

In [105]:
## itemsize -> provides with the size of a unique element inside our array in bytes

In [106]:
## dtype ---> It provides us with the idea about the data type of every item inside our array

In [107]:
np.array([[1,2,3],[4,5,6]]).dtype

dtype('int64')

## astype() --> It will be helping us out with figuring out the data type of the column in the dataset in pandas and it will be used in NumPy as well for getting the data type changed of our overall array 

In [108]:
array = np.arange(1,10).reshape(3,3)

In [109]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
array.dtype

dtype('int64')

In [111]:
array.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [112]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Mathematical Operations in NumPy

#### scalar operations ---> A scalar value operation will be done with the array or a numeric value (eg. 1,4)

In [113]:
array = np.random.random((3,3))*100

In [114]:
array

array([[67.67575   , 40.16013167, 86.11588476],
       [ 4.11296195, 22.42298522, 10.09786361],
       [40.36065165, 95.06099459, 27.56968005]])

In [115]:
np.round(array)

array([[68., 40., 86.],
       [ 4., 22., 10.],
       [40., 95., 28.]])

In [117]:
array = np.round(array)   # rounding of each element to an integer

In [118]:
array

array([[68., 40., 86.],
       [ 4., 22., 10.],
       [40., 95., 28.]])

In [120]:
array = array.astype('int32')

In [121]:
array

array([[68, 40, 86],
       [ 4, 22, 10],
       [40, 95, 28]], dtype=int32)

In [122]:
## Scalar operations with our matrix or array

In [123]:
array + 2

array([[70, 42, 88],
       [ 6, 24, 12],
       [42, 97, 30]], dtype=int32)

In [124]:
array - 5

array([[63, 35, 81],
       [-1, 17,  5],
       [35, 90, 23]], dtype=int32)

In [125]:
array *2

array([[136,  80, 172],
       [  8,  44,  20],
       [ 80, 190,  56]], dtype=int32)

In [126]:
array/2

array([[34. , 20. , 43. ],
       [ 2. , 11. ,  5. ],
       [20. , 47.5, 14. ]])

In [127]:
# We can apply scalar operations with the array in terms of arithmetic operations

In [128]:
array

array([[68, 40, 86],
       [ 4, 22, 10],
       [40, 95, 28]], dtype=int32)

In [129]:
array>60

array([[ True, False,  True],
       [False, False, False],
       [False,  True, False]])

In [ ]:
## Vector Operations : Operations will be in between the given number of matrices

In [131]:
arr_1 = np.arange(1,17).reshape(4,4)

In [133]:
arr_2 = np.arange(17,33).reshape(4,4)

In [134]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [135]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [136]:
arr_1+arr_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [137]:
arr_2 - arr_1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [138]:
arr_1 * arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

## Important Functions in NumPy for Machine Learning and Data Science

In [140]:
## max() --> It is going to be used to calculate the max value inside a matrix or an array
## Syntax for max() --> np.max(array) 

In [141]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [142]:
max_val = np.max(arr_1)

In [144]:
print(max_val)

16


In [147]:
array_data = np.round(np.random.random((4,4))*100).astype('int32')

In [148]:
array_data

array([[19, 65, 50, 48],
       [49, 68, 27, 30],
       [11, 27, 75, 49],
       [72, 36,  8, 87]], dtype=int32)

#### axis ---> It provides us with the idea about the any operation value inside a specific row or column or we can get a specific value row wise or column wise

#### axis = 0 --> column wise operation
#### axis = 1 --> row wise operation

In [149]:
array_data

array([[19, 65, 50, 48],
       [49, 68, 27, 30],
       [11, 27, 75, 49],
       [72, 36,  8, 87]], dtype=int32)

In [150]:
np.max(array_data)

np.int32(87)

In [151]:
np.max(array_data, axis=0) #column wise operation

array([72, 68, 75, 87], dtype=int32)

In [152]:
np.max(array_data, axis = 1)

array([65, 68, 75, 87], dtype=int32)

In [153]:
## min() --> It will be used for calculating the minimum value from the matrix or array
# syntax -> np.min(array) 

In [154]:
array_data

array([[19, 65, 50, 48],
       [49, 68, 27, 30],
       [11, 27, 75, 49],
       [72, 36,  8, 87]], dtype=int32)

In [155]:
np.min(array_data)

np.int32(8)

In [156]:
np.min(array_data, axis = 0)

array([11, 27,  8, 30], dtype=int32)

In [157]:
np.min(array_data, axis = 1)

array([19, 27, 11,  8], dtype=int32)

In [158]:
array = np.arange(1,10)

In [159]:
np.max(array)

np.int64(9)

In [160]:
np.min(array)

np.int64(1)

In [161]:
## sum --> calculates the sum of all of the values of a given matrix
# syntax --> np.sum(array)

In [162]:
array_data

array([[19, 65, 50, 48],
       [49, 68, 27, 30],
       [11, 27, 75, 49],
       [72, 36,  8, 87]], dtype=int32)

In [163]:
np.sum(array_data)

np.int64(721)

In [164]:
np.sum(array_data, axis = 0)

array([151, 196, 160, 214])

In [165]:
np.sum(array_data, axis = 1)

array([182, 174, 162, 203])

In [166]:
array_data

array([[19, 65, 50, 48],
       [49, 68, 27, 30],
       [11, 27, 75, 49],
       [72, 36,  8, 87]], dtype=int32)

In [167]:
## prod() --> helps with calculating the product of all values inside the matrix
## syntax --> np.prod()

In [168]:
np.prod(array_data)

np.int64(472130081120649216)

In [169]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
np.prod(array)

np.int64(362880)

In [174]:
np.prod(array_data, axis = 1) # row wise product

array([2964000, 2698920, 1091475, 1804032])

In [175]:
np.prod(array_data, axis = 0)  # column wise product

array([ 737352, 4296240,  810000, 6138720])