# Statistical Functions in NumPy

In [1]:
## mean() --> syntax for mean() --> np.mean() --> mean of all values inside the array or matrix 

In [2]:
import numpy as np

In [4]:
array_data = np.round(np.random.random((4,4))*100).astype('int32') 

In [5]:
array_data

array([[38, 81, 57, 12],
       [23, 46, 97, 71],
       [76, 53, 48, 89],
       [77,  8, 35, 24]], dtype=int32)

In [6]:
np.mean(array_data)

np.float64(52.1875)

In [7]:
np.mean(array_data, axis = 0) #column wise mean

array([53.5 , 47.  , 59.25, 49.  ])

In [8]:
np.mean(array_data, axis = 1)

array([47.  , 59.25, 66.5 , 36.  ])

In [9]:
## std() --> will provide the standard deviation of all the values of the matrix or array

In [10]:
array_data

array([[38, 81, 57, 12],
       [23, 46, 97, 71],
       [76, 53, 48, 89],
       [77,  8, 35, 24]], dtype=int32)

In [11]:
np.std(array_data)

np.float64(26.833325245857996)

In [12]:
np.std(array_data, axis = 0)

array([23.60614327, 26.04803256, 23.15572283, 31.92961008])

In [13]:
np.std(array_data, axis = 1)

array([25.30810147, 27.6258484 , 16.74066904, 25.54407955])

In [14]:
## median --> calculate median of all the values in the array or matrix
## syntax for median --> np.median()

In [15]:
array_data

array([[38, 81, 57, 12],
       [23, 46, 97, 71],
       [76, 53, 48, 89],
       [77,  8, 35, 24]], dtype=int32)

In [16]:
np.median(array_data)

np.float64(50.5)

In [17]:
np.median(array_data, axis = 0)

array([57. , 49.5, 52.5, 47.5])

In [18]:
np.median(array_data, axis = 1)

array([47.5, 58.5, 64.5, 29.5])

In [19]:
## var --> it helps with calculating the variance of all values inside the array or matrix

In [20]:
## syntax --> np.var()

In [21]:
array_data

array([[38, 81, 57, 12],
       [23, 46, 97, 71],
       [76, 53, 48, 89],
       [77,  8, 35, 24]], dtype=int32)

In [22]:
np.var(array_data)

np.float64(720.02734375)

## Trignometric Functions

In [26]:
## sin() --> sin value for the value we are going to pass inside it --> np.sin()

In [24]:
np.sin(0)

np.float64(0.0)

In [ ]:
np.sin(60)

np.float64(-0.3048106211022167)

In [27]:
np.tan(45)

np.float64(1.6197751905438615)

In [42]:
np.cos(12)

np.float64(0.8438539587324921)

In [43]:
np.sin(array_data)

array([[ 0.29636858, -0.62988799,  0.43616476, -0.53657292],
       [-0.8462204 ,  0.90178835,  0.37960774,  0.95105465],
       [ 0.56610764,  0.39592515, -0.76825466,  0.86006941],
       [ 0.99952016,  0.98935825, -0.42818267, -0.90557836]])

## Dot Product of Matrices
#### syntax for dot product -> np.dot(matrix1, matrix2)

In [38]:
matrix1 = np.round(np.random.random((3,4))*100).astype('int32')
matrix2 = np.round(np.random.random((4,3))*100).astype('int32')

In [39]:
matrix1

array([[81, 99, 75, 57],
       [94, 27, 52, 65],
       [57, 59, 57, 32]], dtype=int32)

In [40]:
matrix2

array([[16, 60, 14],
       [ 4, 61, 33],
       [37, 60, 97],
       [40, 44, 76]], dtype=int32)

In [41]:
np.dot(matrix1, matrix2)

array([[ 6747, 17907, 16008],
       [ 6136, 13267, 12191],
       [ 4537, 11847, 10706]], dtype=int32)

In [44]:
## log() --> To calculate the log of all values of our matrix
## syntax for log --> np.log()

In [45]:
matrix1

array([[81, 99, 75, 57],
       [94, 27, 52, 65],
       [57, 59, 57, 32]], dtype=int32)

In [46]:
np.log(matrix1)

array([[4.39444915, 4.59511985, 4.31748811, 4.04305127],
       [4.54329478, 3.29583687, 3.95124372, 4.17438727],
       [4.04305127, 4.07753744, 4.04305127, 3.4657359 ]])

In [47]:
## exp() ---> exponential of all values inside the matrix
## syntax --> np.exp()

In [48]:
matrix1

array([[81, 99, 75, 57],
       [94, 27, 52, 65],
       [57, 59, 57, 32]], dtype=int32)

In [49]:
np.exp(matrix1)

array([[1.50609731e+35, 9.88903032e+42, 3.73324200e+32, 5.68572000e+24],
       [6.66317622e+40, 5.32048241e+11, 3.83100800e+22, 1.69488924e+28],
       [5.68572000e+24, 4.20121040e+25, 5.68572000e+24, 7.89629602e+13]])

#### it helps us with rounding off the float values to its nearest possible integer value
#### syntax for round ---> np.round()
#### round off value for 1.7 -> 2
#### round off value for 1.3 -> 1

In [54]:
array = np.random.random((3,4))

In [57]:
array = array*10

In [58]:
array

array([[2.93805446, 3.43941142, 2.88266027, 4.04742237],
       [0.3617198 , 9.35143156, 6.80982885, 3.76055856],
       [9.20606944, 4.1064913 , 8.54821901, 2.31060307]])

In [59]:
np.round(array)

array([[3., 3., 3., 4.],
       [0., 9., 7., 4.],
       [9., 4., 9., 2.]])

In [60]:
# round() --> 1.6-> 2, 1.3->1
# ceil()  --> 1.6-> 2, 1.3->2
# floor() --> 1.6-> 1, 1.3->1

In [61]:
## ceil() -> next corresponding integer value -> np.ceil()

In [62]:
array

array([[2.93805446, 3.43941142, 2.88266027, 4.04742237],
       [0.3617198 , 9.35143156, 6.80982885, 3.76055856],
       [9.20606944, 4.1064913 , 8.54821901, 2.31060307]])

In [63]:
np.ceil(array)

array([[ 3.,  4.,  3.,  5.],
       [ 1., 10.,  7.,  4.],
       [10.,  5.,  9.,  3.]])

In [65]:
## floor() -> it can provide us with the previous integer value
## syntax -> np.floor()

In [66]:
array

array([[2.93805446, 3.43941142, 2.88266027, 4.04742237],
       [0.3617198 , 9.35143156, 6.80982885, 3.76055856],
       [9.20606944, 4.1064913 , 8.54821901, 2.31060307]])

In [67]:
np.floor(array)

array([[2., 3., 2., 4.],
       [0., 9., 6., 3.],
       [9., 4., 8., 2.]])

In [69]:
## Transpose :-->  It calculates the transpose of the given matrix
## Transpose syntax --> np.transpose(arr) or arr.T
## Transpose -> (i,j) --> (j,i) ----> (3,4) ----> T ----> (4,3)

In [72]:
array = np.arange(1,13).reshape(3,4)

In [73]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [76]:
np.transpose(array)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [77]:
## Ravel() --> np.ravel() --> convert nd array into 1D array

In [78]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
array.ndim

2

In [80]:
np.ravel(array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Indexing and Slicing Processes in NumPy

In [81]:
## Indexing ---> lists[,size-1] ---> To have the access over the values 

In [83]:
array = np.round(np.random.random((5,5))*100).astype('int32')

In [84]:
array

array([[68, 23, 56, 52, 39],
       [31,  7, 52, 18, 91],
       [29, 41, 77, 27, 75],
       [42, 64, 23, 38, 77],
       [74, 24, 14, 29, 12]], dtype=int32)

In [85]:
array_one = np.arange(1,10)

In [86]:
array_one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
array_one[6]

np.int64(7)

In [89]:
array_one[8]

np.int64(9)

In [90]:
array

array([[68, 23, 56, 52, 39],
       [31,  7, 52, 18, 91],
       [29, 41, 77, 27, 75],
       [42, 64, 23, 38, 77],
       [74, 24, 14, 29, 12]], dtype=int32)

In [95]:
## Indexing in 2D array : [row, collumn]
## Indexing in 3D array : [z-axis, x-axis, y-axis]

In [96]:
array[4][2]

np.int32(14)

In [97]:
array[2,3] #[row, column] or [row][column]

np.int32(27)

In [98]:
array_three = np.arange(1,9).reshape(2,2,2)

In [99]:
array_three

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [100]:
# you want to access 6
array_three[1,0,1]

np.int64(6)

In [101]:
array_three[0,1,0]

np.int64(3)

In [102]:
array

array([[68, 23, 56, 52, 39],
       [31,  7, 52, 18, 91],
       [29, 41, 77, 27, 75],
       [42, 64, 23, 38, 77],
       [74, 24, 14, 29, 12]], dtype=int32)

In [103]:
## Slicing ---> similar approach just like the list [:]
## 2D Array ---> [row_1:row2, col_1:col_2]
## 3D Array ---> [z-axis_1:z_axis_2, row_1:row_2, col_1:col_2]

In [104]:
array[:,2]

array([56, 52, 77, 23, 14], dtype=int32)

In [105]:
array[0,:]

array([68, 23, 56, 52, 39], dtype=int32)

In [106]:
array

array([[68, 23, 56, 52, 39],
       [31,  7, 52, 18, 91],
       [29, 41, 77, 27, 75],
       [42, 64, 23, 38, 77],
       [74, 24, 14, 29, 12]], dtype=int32)

In [109]:
array[2:4,3:]

array([[27, 75],
       [38, 77]], dtype=int32)

In [110]:
array[2:,1:4]

array([[41, 77, 27],
       [64, 23, 38],
       [24, 14, 29]], dtype=int32)

In [111]:
## Iterating over an array

In [112]:
array = np.arange(1,10)

In [113]:
for i in array:
    print(i)

1
2
3
4
5
6
7
8
9


In [114]:
array = np.arange(1,17).reshape(4,4)

In [115]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [117]:
for i in array:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [116]:
for i in array:
    for j in i:
        print(j,end=" ")
    print("\n")


1 2 3 4 

5 6 7 8 

9 10 11 12 

13 14 15 16 



In [119]:
array = np.arange(1,28).reshape(3,3,3)

In [120]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [122]:
for i in array:  # prints 2D array's in series this way
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


In [123]:
## nditer() --> It can help us out with iterating over every value in a nd array
## np.nditer()

In [124]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [125]:
for i in np.nditer(array):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [126]:
# 1D Array : value by value on iteration
# 2D Array : Row by Row on iteration
# 3D Array : 2D Array by 2D Array

# Stacking and Splitting in Array

In [ ]:
## Stacking --> joining the arrays together
## Horizontal Stacking --> Row by Row joining is done --> hstack()
## Vertical Stacking --> column by column joining is done --> vstack(a)

In [128]:
array_one = np.arange(1,13).reshape(3,4)

In [129]:
array_one

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [130]:
array_two = np.arange(13,25).reshape(3,4)

In [131]:
array_two

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [133]:
# lets do horizontal stack
horizontal_array = np.hstack((array_one, array_two))

In [134]:
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [135]:
horizontal_array = np.hstack((array_one, array_two, array_one, array_two))

In [136]:
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16,  1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20,  5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24,  9, 10, 11, 12, 21, 22, 23, 24]])

In [137]:
vertical_array = np.vstack((array_one, array_two))

In [138]:
vertical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [139]:
## Horizontal Split --> np.hsplit(array, no. of parts you want your array to be splitted at)
## Vertical Split --> np.vsplit(array, no. of parts you want your array to be splitted at)

In [143]:
np.hsplit(vertical_array, 4)

[array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17],
        [21]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]]),
 array([[ 4],
        [ 8],
        [12],
        [16],
        [20],
        [24]])]

In [144]:
np.hsplit(vertical_array, 2) # how many splits at parameter 2

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [145]:
np.vsplit(vertical_array,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [147]:
ar1, ar2, ar3 = np.vsplit(vertical_array,3)

In [148]:
ar1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [149]:
ar2

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [150]:
ar3

array([[17, 18, 19, 20],
       [21, 22, 23, 24]])

In [152]:
for i in np.vsplit(vertical_array,3):
    print(i)
    print("\n")

[[1 2 3 4]
 [5 6 7 8]]


[[ 9 10 11 12]
 [13 14 15 16]]


[[17 18 19 20]
 [21 22 23 24]]


